server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: caddy_access_json
    static_configs:
      - targets: [localhost]
        labels:
          job: caddy
          __path__: /var/log/caddy/access.log
    pipeline_stages:
      - json:
          expressions:
            ts: ts
            request: request
            status: status
            size: size
            duration: duration
            remote_ip: remote_ip
            method: request.method
            uri: request.uri
            host: request.host
            user_agent: request.headers.User-Agent
            referer: request.headers.Referer
      - labels:
          status:
          method:
          host:
      - timestamp:
          source: ts
          format: RFC3339Nano

